# Config file for parameters and supplementary files

# Preprocessing 
adapter_sequence_1: CTGTCTCTTATACACATCTCCGAGCCCACGAGAC
adapter_sequence_2: CTGTCTCTTATACACATCTGACGCTGCCGACGA

# Alignment
aligner: minimap2 # minimap2 or bwa
reference_genome: /gsc/resources/Homo_sapiens_genomes/hg38_no_alt/genome/fasta/hg38_no_alt.fa

# QC - Fastq screen
fastq_screen_reference:
  contaminate:
    /projects/steiflab/scratch/glchang/bowtie2_reference/Adapters/Contaminants
  arabidopsis:
    /projects/steiflab/scratch/glchang/bowtie2_reference/Arabidopsis/Arabidopsis_thaliana.TAIR10
  drosophila:
    /projects/steiflab/scratch/glchang/bowtie2_reference/Drosophila/BDGP6
  e_coli:
    /projects/steiflab/scratch/glchang/bowtie2_reference/E_coli/Ecoli
  human:
    /projects/steiflab/scratch/glchang/bowtie2_reference/Human/Homo_sapiens.GRCh38
  lambda:
    /projects/steiflab/scratch/glchang/bowtie2_reference/Lambda/Lambda
  mitochondria:
    /projects/steiflab/scratch/glchang/bowtie2_reference/Mitochondria/mitochondria
  mouse:
    /projects/steiflab/scratch/glchang/bowtie2_reference/Mouse/Mus_musculus.GRCm38
  phiX:
    /projects/steiflab/scratch/glchang/bowtie2_reference/PhiX/phi_plus_SNPs
  rat:
    /projects/steiflab/scratch/glchang/bowtie2_reference/Rat/Rnor_6.0
  vector:
    /projects/steiflab/scratch/glchang/bowtie2_reference/Vectors/Vectors
  worm:
    /projects/steiflab/scratch/glchang/bowtie2_reference/Worm/Caenorhabditis_elegans.WBcel235
  yeast:
    /projects/steiflab/scratch/glchang/bowtie2_reference/Yeast/Saccharomyces_cerevisiae.R64-1-1
     

    